# Name of the workflow (shown in GitHub Actions UI)
name: build-and-lint

# WHEN this workflow  runs
on:
  # Runs when code is pushed to these branches
  push:
    branches: [main, dev]

  # Runs when a pull request targets these branches
  pull_request:
    branches: [main, dev]

# JOBS = group of steps that run on a machine
jobs:
  build-and-lint:

    # Operating system machine provided by GitHub
    runs-on: ubuntu-latest

    # STEPS = individual tasks inside this job (run one by one)
    steps:

      # STEP 1: Download your repository code into the VM
      - name: Checkout repo
        uses: actions/checkout@v3
        # Without this, the runner has no project files

      # STEP 2: Install Node.js runtime
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
        # This installs Node.js so npm commands can run

      # STEP 3: Install backend dependencies
      - name: Install backend deps
        working-directory: backend
        run: npm ci
        # npm ci = clean, fast, exact dependency install using package-lock.json

      # STEP 4: Run backend lint checks
      - name: Lint backend
        working-directory: backend
        run: npm run lint -- --max-warnings=0
        # Fails CI if there are ANY warnings or errors in backend code

      # STEP 5: Install frontend dependencies
      - name: Install frontend deps
        working-directory: frontend
        run: npm ci
        # Same as backend but for frontend app

      # STEP 6: Run frontend lint checks
      - name: Lint frontend
        working-directory: frontend
        run: npm run lint -- --max-warnings=0
        # Ensures frontend code quality is clean

      # STEP 7: Build backend Docker image
      - name: Build backend Docker image
        run: docker build -t chatbackend ./backend
        # Creates a Docker image for backend app

      # STEP 8: Build frontend Docker image
      - name: Build frontend Docker image
        run: docker build -t chatfrontend ./frontend
        # Creates Docker image for frontend app